image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    command: |
      tfenv use 1.6.1
      echo "Environment setup complete."
  - name: Create dot aws folder
    command: |
      mkdir -p $HOME/.aws
      echo "[theia]" > $HOME/.aws/credentials
      echo "[theia]" > $HOME/.aws/config
      echo "region=us-west-2" >> $HOME/.aws/config
      echo "Created default config for aws"
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform